run:
  timeout: 5m
  tests: true
  go: "1.23"

linters:
  disable:
    # TODO: 점진적으로 수정 후 활성화
    # 기존 코드에 에러 반환값 미처리가 많아 일시 비활성화
    - errcheck
    # TODO: Go 1.25.4 호환되는 golangci-lint 버전 출시 후 활성화
    # 현재 golangci-lint가 Go 1.24로 빌드되어 go.mod의 1.25.4를 인식 못함
    - typecheck

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA1019"  # deprecated 함수 사용 경고 무시 (AWS SDK v2 마이그레이션 필요)
      - "-SA1029"  # context key 타입 경고 무시
  gosimple:
    checks:
      - "all"
      - "-S1009"  # nil check before len() 경고 무시

issues:
  # 테스트 파일에서는 일부 규칙 완화
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
