version: '3.8'

services:
  kanban:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@wealist-postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD}@wealist-redis:6379/0
      ENV: ${ENV:-development}
      DEBUG: ${DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "${KANBAN_PORT:-8000}:8000"
    volumes:
      - .:/app
    networks:
      - wealist-network
    restart: unless-stopped
    # depends_on은 external network에서 작동하지 않음
    # 인프라가 먼저 실행되어 있어야 함

networks:
  wealist-network:
    external: true
